version: '3.8'

services:
  ttlock:
    image: eritque/chastease:latest
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /root/chastease/QRCodes:/app/qrcodes
      - /root/chastease/instance:/app/instance
    environment:
      - FLASK_ENV=production

