"""baseline_schema_squash

Revision ID: 0031
Revises:
Create Date: 2026-03-30 17:48:11.634091
"""
from alembic import op
import sqlalchemy as sa
from app.services.secret_crypto import EncryptedText


# revision identifiers, used by Alembic.
revision = '0031'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('password_salt', sa.String(length=32), nullable=False),
    sa.Column('session_token', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('setup_completed', sa.Boolean(), nullable=False),
    sa.Column('default_player_profile_id', sa.Integer(), nullable=True),
    sa.Column('active_session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['active_session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_player_profile_id'], ['player_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.create_index(op.f('ix_auth_users_id'), 'auth_users', ['id'], unique=False)
    op.create_index(op.f('ix_auth_users_session_token'), 'auth_users', ['session_token'], unique=True)
    op.create_index(op.f('ix_auth_users_username'), 'auth_users', ['username'], unique=True)
    op.create_table('game_module_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=120), nullable=False),
    sa.Column('easy_target_multiplier', sa.Float(), nullable=False),
    sa.Column('hard_target_multiplier', sa.Float(), nullable=False),
    sa.Column('target_randomization_percent', sa.Integer(), nullable=False),
    sa.Column('start_countdown_seconds', sa.Integer(), nullable=False),
    sa.Column('movement_easy_pose_deviation', sa.Float(), nullable=True),
    sa.Column('movement_easy_stillness', sa.Float(), nullable=True),
    sa.Column('movement_medium_pose_deviation', sa.Float(), nullable=True),
    sa.Column('movement_medium_stillness', sa.Float(), nullable=True),
    sa.Column('movement_hard_pose_deviation', sa.Float(), nullable=True),
    sa.Column('movement_hard_stillness', sa.Float(), nullable=True),
    sa.Column('pose_similarity_min_score_easy', sa.Float(), nullable=True),
    sa.Column('pose_similarity_min_score_medium', sa.Float(), nullable=True),
    sa.Column('pose_similarity_min_score_hard', sa.Float(), nullable=True),
    sa.Column('mask_image_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_module_settings_id'), 'game_module_settings', ['id'], unique=False)
    op.create_index(op.f('ix_game_module_settings_module_key'), 'game_module_settings', ['module_key'], unique=True)
    op.create_table('game_posture_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=120), nullable=False),
    sa.Column('posture_key', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('reference_landmarks_json', sa.Text(), nullable=True),
    sa.Column('reference_landmarks_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('target_seconds', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_posture_templates_id'), 'game_posture_templates', ['id'], unique=False)
    op.create_index(op.f('ix_game_posture_templates_module_key'), 'game_posture_templates', ['module_key'], unique=False)
    op.create_table('llm_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_key', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('api_url', sa.String(length=500), nullable=True),
    sa.Column('api_key', EncryptedText(), nullable=True),
    sa.Column('chat_model', sa.String(length=120), nullable=True),
    sa.Column('vision_model', sa.String(length=120), nullable=True),
    sa.Column('profile_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_key')
    )
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('media_kind', sa.String(length=30), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_id'), 'media_assets', ['id'], unique=False)
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('speech_style_tone', sa.String(length=60), nullable=True),
    sa.Column('speech_style_dominance', sa.String(length=60), nullable=True),
    sa.Column('formatting_style', sa.String(length=30), nullable=True),
    sa.Column('verbosity_style', sa.String(length=30), nullable=True),
    sa.Column('praise_style', sa.String(length=30), nullable=True),
    sa.Column('repetition_guard', sa.String(length=30), nullable=True),
    sa.Column('context_exposition_style', sa.String(length=30), nullable=True),
    sa.Column('behavior_profile_json', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('strictness_level', sa.Integer(), nullable=False),
    sa.Column('avatar_media_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['avatar_media_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_id'), 'personas', ['id'], unique=False)
    op.create_table('player_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_user_id', sa.Integer(), nullable=True),
    sa.Column('nickname', sa.String(length=120), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=False),
    sa.Column('preferences_json', sa.Text(), nullable=False),
    sa.Column('soft_limits_json', sa.Text(), nullable=False),
    sa.Column('hard_limits_json', sa.Text(), nullable=False),
    sa.Column('reaction_patterns_json', sa.Text(), nullable=False),
    sa.Column('needs_json', sa.Text(), nullable=False),
    sa.Column('avatar_media_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['auth_user_id'], ['auth_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['avatar_media_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_profiles_id'), 'player_profiles', ['id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('lorebook_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('phases_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('tags_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('behavior_profile_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('player_profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('lock_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_end_actual', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timer_frozen', sa.Boolean(), nullable=False),
    sa.Column('freeze_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('min_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('max_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('hygiene_limit_daily', sa.Integer(), nullable=True),
    sa.Column('hygiene_limit_weekly', sa.Integer(), nullable=True),
    sa.Column('hygiene_limit_monthly', sa.Integer(), nullable=True),
    sa.Column('hygiene_opening_max_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=True),
    sa.Column('llm_api_url', sa.String(length=500), nullable=True),
    sa.Column('llm_api_key', EncryptedText(), nullable=True),
    sa.Column('llm_chat_model', sa.String(length=120), nullable=True),
    sa.Column('llm_vision_model', sa.String(length=120), nullable=True),
    sa.Column('llm_profile_active', sa.Boolean(), nullable=False),
    sa.Column('relationship_state_json', EncryptedText(), nullable=True),
    sa.Column('protocol_state_json', EncryptedText(), nullable=True),
    sa.Column('scene_state_json', EncryptedText(), nullable=True),
    sa.Column('ws_auth_token', sa.String(length=80), nullable=True),
    sa.Column('ws_auth_token_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['player_profile_id'], ['player_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ws_auth_token')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parameters_snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.create_table('game_posture_module_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posture_template_id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['posture_template_id'], ['game_posture_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('posture_template_id', 'module_key', name='uq_game_posture_module_assignment')
    )
    op.create_index(op.f('ix_game_posture_module_assignments_id'), 'game_posture_module_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_game_posture_module_assignments_module_key'), 'game_posture_module_assignments', ['module_key'], unique=False)
    op.create_index(op.f('ix_game_posture_module_assignments_posture_template_id'), 'game_posture_module_assignments', ['posture_template_id'], unique=False)
    op.create_table('game_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=120), nullable=False),
    sa.Column('difficulty_key', sa.String(length=40), nullable=False),
    sa.Column('initiated_by', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('retry_extension_seconds', sa.Integer(), nullable=False),
    sa.Column('transition_seconds', sa.Integer(), nullable=False),
    sa.Column('max_misses_before_penalty', sa.Integer(), nullable=False),
    sa.Column('miss_count', sa.Integer(), nullable=False),
    sa.Column('session_penalty_seconds', sa.Integer(), nullable=False),
    sa.Column('session_penalty_applied', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_runs_id'), 'game_runs', ['id'], unique=False)
    op.create_index(op.f('ix_game_runs_module_key'), 'game_runs', ['module_key'], unique=False)
    op.create_index(op.f('ix_game_runs_session_id'), 'game_runs', ['session_id'], unique=False)
    op.create_table('hygiene_openings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('relocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('old_seal_number', sa.String(length=120), nullable=True),
    sa.Column('new_seal_number', sa.String(length=120), nullable=True),
    sa.Column('overrun_seconds', sa.Integer(), nullable=False),
    sa.Column('penalty_seconds', sa.Integer(), nullable=False),
    sa.Column('penalty_applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hygiene_openings_id'), 'hygiene_openings', ['id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['auth_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_key'), 'items', ['key'], unique=True)
    op.create_index(op.f('ix_items_owner_user_id'), 'items', ['owner_user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('prompt_templates_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('persona_task_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline_minutes', sa.Integer(), nullable=True),
    sa.Column('requires_verification', sa.Boolean(), nullable=False),
    sa.Column('verification_criteria', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('tags_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_task_templates_id'), 'persona_task_templates', ['id'], unique=False)
    op.create_index(op.f('ix_persona_task_templates_persona_id'), 'persona_task_templates', ['persona_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_session_id'), 'push_subscriptions', ['session_id'], unique=False)
    op.create_table('safety_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_logs_id'), 'safety_logs', ['id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('consequence_type', sa.String(length=50), nullable=True),
    sa.Column('consequence_value', sa.Integer(), nullable=True),
    sa.Column('consequence_applied_seconds', sa.Integer(), nullable=True),
    sa.Column('consequence_applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requires_verification', sa.Boolean(), nullable=False),
    sa.Column('verification_criteria', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('contract_addenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('proposed_changes_json', sa.Text(), nullable=False),
    sa.Column('change_description', sa.Text(), nullable=False),
    sa.Column('proposed_by', sa.String(length=20), nullable=False),
    sa.Column('player_consent', sa.String(length=20), nullable=False),
    sa.Column('player_consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_addenda_id'), 'contract_addenda', ['id'], unique=False)
    op.create_table('game_run_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('posture_key', sa.String(length=120), nullable=False),
    sa.Column('posture_name', sa.String(length=200), nullable=False),
    sa.Column('posture_image_url', sa.String(length=500), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('target_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('verification_count', sa.Integer(), nullable=False),
    sa.Column('retry_of_step_id', sa.Integer(), nullable=True),
    sa.Column('last_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['retry_of_step_id'], ['game_run_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['game_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_run_steps_id'), 'game_run_steps', ['id'], unique=False)
    op.create_index(op.f('ix_game_run_steps_order_index'), 'game_run_steps', ['order_index'], unique=False)
    op.create_index(op.f('ix_game_run_steps_run_id'), 'game_run_steps', ['run_id'], unique=False)
    op.create_table('scenario_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('default_quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('phase_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_items_id'), 'scenario_items', ['id'], unique=False)
    op.create_index(op.f('ix_scenario_items_item_id'), 'scenario_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_scenario_items_scenario_id'), 'scenario_items', ['scenario_id'], unique=False)
    op.create_table('seal_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('hygiene_opening_id', sa.Integer(), nullable=True),
    sa.Column('seal_number', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hygiene_opening_id'], ['hygiene_openings.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seal_history_id'), 'seal_history', ['id'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('requested_seal_number', sa.String(length=120), nullable=True),
    sa.Column('observed_seal_number', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('linked_task_id', sa.Integer(), nullable=True),
    sa.Column('verification_criteria', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['linked_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_id'), 'verifications', ['id'], unique=False)
    op.create_table('session_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('linked_scenario_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_scenario_item_id'], ['scenario_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_items_id'), 'session_items', ['id'], unique=False)
    op.create_index(op.f('ix_session_items_item_id'), 'session_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_session_items_session_id'), 'session_items', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_items_session_id'), table_name='session_items')
    op.drop_index(op.f('ix_session_items_item_id'), table_name='session_items')
    op.drop_index(op.f('ix_session_items_id'), table_name='session_items')
    op.drop_table('session_items')
    op.drop_index(op.f('ix_verifications_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_seal_history_id'), table_name='seal_history')
    op.drop_table('seal_history')
    op.drop_index(op.f('ix_scenario_items_scenario_id'), table_name='scenario_items')
    op.drop_index(op.f('ix_scenario_items_item_id'), table_name='scenario_items')
    op.drop_index(op.f('ix_scenario_items_id'), table_name='scenario_items')
    op.drop_table('scenario_items')
    op.drop_index(op.f('ix_game_run_steps_run_id'), table_name='game_run_steps')
    op.drop_index(op.f('ix_game_run_steps_order_index'), table_name='game_run_steps')
    op.drop_index(op.f('ix_game_run_steps_id'), table_name='game_run_steps')
    op.drop_table('game_run_steps')
    op.drop_index(op.f('ix_contract_addenda_id'), table_name='contract_addenda')
    op.drop_table('contract_addenda')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_safety_logs_id'), table_name='safety_logs')
    op.drop_table('safety_logs')
    op.drop_index(op.f('ix_push_subscriptions_session_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_persona_task_templates_persona_id'), table_name='persona_task_templates')
    op.drop_index(op.f('ix_persona_task_templates_id'), table_name='persona_task_templates')
    op.drop_table('persona_task_templates')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_items_owner_user_id'), table_name='items')
    op.drop_index(op.f('ix_items_key'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_hygiene_openings_id'), table_name='hygiene_openings')
    op.drop_table('hygiene_openings')
    op.drop_index(op.f('ix_game_runs_session_id'), table_name='game_runs')
    op.drop_index(op.f('ix_game_runs_module_key'), table_name='game_runs')
    op.drop_index(op.f('ix_game_runs_id'), table_name='game_runs')
    op.drop_table('game_runs')
    op.drop_index(op.f('ix_game_posture_module_assignments_posture_template_id'), table_name='game_posture_module_assignments')
    op.drop_index(op.f('ix_game_posture_module_assignments_module_key'), table_name='game_posture_module_assignments')
    op.drop_index(op.f('ix_game_posture_module_assignments_id'), table_name='game_posture_module_assignments')
    op.drop_table('game_posture_module_assignments')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_player_profiles_id'), table_name='player_profiles')
    op.drop_table('player_profiles')
    op.drop_index(op.f('ix_personas_id'), table_name='personas')
    op.drop_table('personas')
    op.drop_index(op.f('ix_media_assets_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_table('llm_profiles')
    op.drop_index(op.f('ix_game_posture_templates_module_key'), table_name='game_posture_templates')
    op.drop_index(op.f('ix_game_posture_templates_id'), table_name='game_posture_templates')
    op.drop_table('game_posture_templates')
    op.drop_index(op.f('ix_game_module_settings_module_key'), table_name='game_module_settings')
    op.drop_index(op.f('ix_game_module_settings_id'), table_name='game_module_settings')
    op.drop_table('game_module_settings')
    op.drop_index(op.f('ix_auth_users_username'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_session_token'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_id'), table_name='auth_users')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_table('auth_users')
    # ### end Alembic commands ###
