"""empty message

Revision ID: 14798dbdf3ab
Revises: b56a092b03c1
Create Date: 2024-02-18 10:41:34.882260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14798dbdf3ab'
down_revision = 'b56a092b03c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chaster_session',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('keyholder_id', sa.Integer(), nullable=True),
    sa.Column('lock_uuid', sa.String(length=128), nullable=True),
    sa.Column('lock_id', sa.String(length=128), nullable=True),
    sa.Column('lock_status', sa.String(length=16), nullable=True),
    sa.Column('combination_id', sa.String(length=128), nullable=True),
    sa.Column('TTL_username', sa.String(length=128), nullable=True),
    sa.Column('TTL_password_md5', sa.String(length=128), nullable=True),
    sa.Column('TTL_lock_alias', sa.String(length=128), nullable=True),
    sa.Column('TTL_lock_id', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['keyholder_id'], ['benutzer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['benutzer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('extension_id', sa.INTEGER(), nullable=False),
    sa.Column('benutzer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], ),
    sa.PrimaryKeyConstraint('extension_id')
    )
    op.drop_table('chaster_session')
    # ### end Alembic commands ###
