"""empty message

Revision ID: 3d0baedcb642
Revises: 60b0dc29ce7d
Create Date: 2023-12-30 18:33:34.366866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0baedcb642'
down_revision = '60b0dc29ce7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benutzer_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CA_keyholder_id', sa.String(length=128), nullable=True))
        batch_op.drop_column('CA_keyholdername_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benutzer_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CA_keyholdername_id', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('CA_keyholder_id')

    # ### end Alembic commands ###
