"""empty message

Revision ID: 4460099ccdb0
Revises: ee5b64359253
Create Date: 2024-01-19 09:31:19.058585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4460099ccdb0'
down_revision = 'ee5b64359253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.alter_column('journal_id',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.alter_column('journal_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
