"""empty message

Revision ID: 64ac6f4016f2
Revises: e379c3179bf9
Create Date: 2023-12-20 22:41:04.920111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ac6f4016f2'
down_revision = 'e379c3179bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benutzer_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TTL_lock_alias', sa.String(length=128), nullable=True))
        batch_op.drop_column('TTL_lock_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benutzer_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TTL_lock_id', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('TTL_lock_alias')

    # ### end Alembic commands ###
