"""empty message

Revision ID: 992f5a697993
Revises: 
Create Date: 2023-12-29 10:19:06.428271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992f5a697993'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benutzer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('oauth2_token', sa.String(length=256), nullable=True),
    sa.Column('oauth2_refresh_token', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('benutzer_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benutzer_id', sa.Integer(), nullable=True),
    sa.Column('CA_username', sa.String(length=128), nullable=True),
    sa.Column('CA_keyholdername', sa.String(length=128), nullable=True),
    sa.Column('CA_user_id', sa.String(length=128), nullable=True),
    sa.Column('CA_lock_id', sa.String(length=128), nullable=True),
    sa.Column('CA_lock_status', sa.String(length=16), nullable=True),
    sa.Column('CA_combination_id', sa.String(length=128), nullable=True),
    sa.Column('TTL_username', sa.String(length=128), nullable=True),
    sa.Column('TTL_password_md5', sa.String(length=128), nullable=True),
    sa.Column('TTL_lock_alias', sa.String(length=128), nullable=True),
    sa.Column('TTL_access_token', sa.String(length=256), nullable=True),
    sa.Column('TTL_refresh_token', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('benutzer_config')
    op.drop_table('benutzer')
    # ### end Alembic commands ###
