"""empty message

Revision ID: b9ea3e2d6fa2
Revises: 8e3b975cd055
Create Date: 2024-01-11 11:26:03.663427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ea3e2d6fa2'
down_revision = '8e3b975cd055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benutzer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CA_lasthist_id', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('benutzer', schema=None) as batch_op:
        batch_op.drop_column('CA_lasthist_id')

    # ### end Alembic commands ###
