"""empty message

Revision ID: bb0fcbf1315c
Revises: 
Create Date: 2024-01-24 16:04:36.998259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0fcbf1315c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benutzer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('avatarUrl', sa.String(length=100), nullable=True),
    sa.Column('lock_uuid', sa.String(length=128), nullable=True),
    sa.Column('CA_username', sa.String(length=128), nullable=True),
    sa.Column('CA_keyholdername', sa.String(length=128), nullable=True),
    sa.Column('CA_keyholder_id', sa.String(length=128), nullable=True),
    sa.Column('CA_user_id', sa.String(length=128), nullable=True),
    sa.Column('CA_lock_id', sa.String(length=128), nullable=True),
    sa.Column('CA_lock_status', sa.String(length=16), nullable=True),
    sa.Column('CA_combination_id', sa.String(length=128), nullable=True),
    sa.Column('TTL_username', sa.String(length=128), nullable=True),
    sa.Column('TTL_password_md5', sa.String(length=128), nullable=True),
    sa.Column('TTL_lock_alias', sa.String(length=128), nullable=True),
    sa.Column('TTL_lock_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('journal',
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('benutzer_id', sa.Integer(), nullable=False),
    sa.Column('hygiene', sa.Boolean(), nullable=True),
    sa.Column('shave', sa.Boolean(), nullable=True),
    sa.Column('edge', sa.Boolean(), nullable=True),
    sa.Column('ruined', sa.Boolean(), nullable=True),
    sa.Column('orgasm', sa.Boolean(), nullable=True),
    sa.Column('horny', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], ),
    sa.PrimaryKeyConstraint('journal_id')
    )
    op.create_table('lock_history',
    sa.Column('hist_id', sa.String(length=128), nullable=False),
    sa.Column('benutzer_id', sa.Integer(), nullable=False),
    sa.Column('lock_id', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.String(length=128), nullable=True),
    sa.Column('extension', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.Column('recordtyp', sa.Integer(), nullable=True),
    sa.Column('recordtypstr', sa.String(length=128), nullable=True),
    sa.Column('recordtypefromlock', sa.Integer(), nullable=True),
    sa.Column('recordtypefromlockstr', sa.String(length=128), nullable=True),
    sa.Column('openSuccess', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], ),
    sa.PrimaryKeyConstraint('hist_id')
    )
    op.create_table('session',
    sa.Column('extension_id', sa.Integer(), nullable=False),
    sa.Column('benutzer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], ),
    sa.PrimaryKeyConstraint('extension_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session')
    op.drop_table('lock_history')
    op.drop_table('journal')
    op.drop_table('benutzer')
    # ### end Alembic commands ###
