"""empty message

Revision ID: bddf45238817
Revises: bf78ea4550ea
Create Date: 2024-01-17 12:25:02.606484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bddf45238817'
down_revision = 'bf78ea4550ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('extension_id', sa.Integer(), nullable=False),
    sa.Column('benutzer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], ),
    sa.PrimaryKeyConstraint('extension_id')
    )
    op.drop_table('ext_session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ext_session',
    sa.Column('extension_id', sa.INTEGER(), nullable=False),
    sa.Column('benutzer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], ),
    sa.PrimaryKeyConstraint('extension_id')
    )
    op.drop_table('session')
    # ### end Alembic commands ###
