"""empty message

Revision ID: cc6db0e7b394
Revises: b9ea3e2d6fa2
Create Date: 2024-01-11 13:07:40.043299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6db0e7b394'
down_revision = 'b9ea3e2d6fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ca__lock__history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benutzer_id', sa.Integer(), nullable=False),
    sa.Column('hist_id', sa.String(length=128), nullable=True),
    sa.Column('lock_id', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.String(length=128), nullable=True),
    sa.Column('extension', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('icon', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ca__lock__history')
    # ### end Alembic commands ###
